---
###############################################
# Solr Host Variables - SRH eCampus
# Nur Abweichungen von defaults/main.yml
###############################################

# Domain & Namen
solr_app_domain: "srh-ecampus.de.solr.elearning-home.de"
solr_core_name: "srhecampus_core"
solr_container_name: "hc-srhecampus-solr"

# Auth (WICHTIG: Mit Vault verschl√ºsseln!)
solr_admin_password: "!hj0iuoefeufhefuj!"
solr_support_password: "!hj0iuoefeufhefuj!"
solr_moodle_password: "efr!ojF!feiXjfeFoj"

# Multi-Tenant Users (optional)
solr_additional_users:
  - username: "dev_admin"
    password: "DevSecurePass123!"
    roles: ["core-admin-{{ solr_core_name }}"]

# Proxy aktivieren
solr_proxy_enabled: true

# System Type
system_type:
  - DBMS
  - Solr
